#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define DW1000_CONF_CHANNEL        4
#define DW1000_CONF_PRF            DWT_PRF_64M
#define DW1000_CONF_PLEN           DWT_PLEN_64
#define DW1000_CONF_PAC            DWT_PAC8
#define DW1000_CONF_SFD_MODE       0
#define DW1000_CONF_DATA_RATE      DWT_BR_6M8
#define DW1000_CONF_PHR_MODE       DWT_PHRMODE_STD
#define DW1000_CONF_PREAMBLE_CODE  17

#define DW1000_CONF_SFD_TIMEOUT    (65 + 32 + 8 - 8)
#define DW1000_CONF_PG_DELAY       0x95

#define DW1000_CONF_SMART_TX_POWER_6M8 0
#define DW1000_CONF_TX_POWER       0x9a9a9a9a

#define STATETIME_CONF_ON 1

#define FS_MACROSLOT 3
#define FS_MINISLOT (42)

#define MAX_LATENCY_FS ((uint32_t)(564 * UUS_TO_DWT_TIME_32))
#define SNIFF_FS_OFF_TIME (26)

#if SNIFF_FS_OFF_TIME != 0
#define SNIFF_FS (1)
#else
#define SNIFF_FS (0)
#endif

#define SLOT_DURATION (20 * UUS_TO_DWT_TIME_32)
#define TIMEOUT (146 * UUS_TO_DWT_TIME_32)

#define TSM_DEFAULT_MINISLOTS_GROUPING 28

#define TSM_CONF_DEFAULT_RXGUARD (1*UUS_TO_DWT_TIME_32)

#define TSM_LOGS_MAX 100

#define GLOBAL_ACK_PERIOD 6

#define WEAVER_LOG_VERBOSE 0

#define WEAVER_BOOT_REDUNDANCY 2

#endif /* PROJECT_CONF_H_ */
